test_factorial (__main__.TestExercice) ... FAIL
test_prefixes (__main__.TestExercice) ... FAIL
test_summation (__main__.TestExercice) ... FAIL

======================================================================
FAIL: test_factorial (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 50, in test_factorial
    'Erreur dans le remplacement de caractère'
AssertionError: Lists differ: [0, 8, 5764801, 3486784401] != [1, 6, 40320, 3628800]

First differing element 0:
0
1

- [0, 8, 5764801, 3486784401]
+ [1, 6, 40320, 3628800] : Erreur dans le remplacement de caractère

======================================================================
FAIL: test_prefixes (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 20, in test_prefixes
    'Mauvaise identification de la parité de la longueur de la chaine'
AssertionError: Lists differ: [''] != ['Jack', 'Kack', 'Lack', 'Mack', 'Nack', 'Oack', 'Pack']

First differing element 0:
''
'Jack'

Second list contains 6 additional elements.
First extra element 1:
'Kack'

- ['']
+ ['Jack', 'Kack', 'Lack', 'Mack', 'Nack', 'Oack', 'Pack'] : Mauvaise identification de la parité de la longueur de la chaine

======================================================================
FAIL: test_summation (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 38, in test_summation
    'Retrait du mauvais caractère'
AssertionError: 0 != 24133 : Retrait du mauvais caractère

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (failures=3)
